### ISSUE TITLE
Publish a syntastic plugin to https://plugins.gradle.org/

### ISSUE THREAD

**Issue by dridi** [Scuilion/gradle-utils#1]
Hi,

Thank you for your plugin, I really love the syntastic feature. It is very pleasant to remove the last bit that was preventing me from writing java code in vim!

I have two cosmetic issues though:
- the other tasks are somewhat unrelated
- this plugin is outstanding compared to other plugins I use

You could instead:
- create a dedicated `gradle-syntastic` github repo
- follow instructions: https://plugins.gradle.org/docs/submit
- publish a "com.github.scuilion.syntastic" plugin

For users, it means a unified syntax:

``` groovy
plugins {
        id "java"
        [...]
        id "com.scuilion.gradle.syntastic" version "0.+"
}

// no need to call apply
// no need for extra buildscript repositories
```

I know it is a selfish request, so I'd totally understand if you don't, but please do :)

Thanks again!

**Comment by Scuilion** [comment]
Dridi,

I was not sure if anyone would be interested in the syntastic. I'll try and pull it out this weekend.

Thanks.

**Comment by dridi** [comment]
Hi Kevin,

Thank you for considering it. I know most Java developers use full-blown IDEs, but those IDEs usually have a poor vim emulation :(

Thanks,
Dridi

**Comment by Scuilion** [comment]
Code moved: https://github.com/Scuilion/gradle-syntastic-plugin/releases/tag/v0.3.2
